"""Remake table users

Revision ID: aeccdcc274ae
Revises: 9460856f403b
Create Date: 2026-01-18 20:44:21.965966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeccdcc274ae'
down_revision: Union[str, Sequence[str], None] = '9460856f403b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Добавляем колонки ВРЕМЕННО nullable
    op.add_column('users', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=True))

    # 2. Заполняем существующих пользователей
    op.execute(
        "UPDATE users SET provider = 'local', provider_id = username WHERE provider IS NULL"
    )

    # 3. Делаем NOT NULL
    op.alter_column('users', 'provider', nullable=False)
    op.alter_column('users', 'provider_id', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
